-- ==============================================================
-- 돼지 거래가격 대시보드 — Supabase 테이블 설정
-- 기존 WBS 프로젝트(wbs_gen_* 테이블)와 공유하는 Supabase 프로젝트에
-- 함께 사용합니다. 테이블명이 겹치지 않도록 pig_ 접두어를 씁니다.
-- Supabase 프로젝트의 SQL Editor에서 이 파일 전체를 실행하세요.
-- ==============================================================

-- 1. 업체 정보
-- 원본 업체정보 엑셀의 모든 컬럼을 그대로 저장한다(통계에 안 쓰이는 컬럼 포함, 팀 확정 방침).
-- ceo_name 이하는 대표자명/주소/연락처/사업자등록번호/담당자 연락처/apikey 등 민감정보를 포함한다.
create table if not exists public.pig_companies (
  company_name         text primary key,
  sido_name            text,
  use_yn               text default 'Y',
  ceo_name             text,
  address              text,
  contact              text,
  manager_name         text,
  business_reg_no      text,
  reg_alarm_yn         text,
  reg_manager1_name    text,
  reg_manager1_contact text,
  reg_manager2_name    text,
  reg_manager2_contact text,
  reg_manager3_name    text,
  reg_manager3_contact text,
  company_id_no        text,
  apikey               text
);

-- 기존에 이미 만들어진 테이블에는 create table if not exists가 컬럼을 추가해주지 않으므로,
-- 이미 pig_companies가 있는 환경(현재 운영 DB 포함)에서도 아래 구문으로 컬럼을 보강한다.
alter table public.pig_companies add column if not exists ceo_name text;
alter table public.pig_companies add column if not exists address text;
alter table public.pig_companies add column if not exists contact text;
alter table public.pig_companies add column if not exists manager_name text;
alter table public.pig_companies add column if not exists business_reg_no text;
alter table public.pig_companies add column if not exists reg_alarm_yn text;
alter table public.pig_companies add column if not exists reg_manager1_name text;
alter table public.pig_companies add column if not exists reg_manager1_contact text;
alter table public.pig_companies add column if not exists reg_manager2_name text;
alter table public.pig_companies add column if not exists reg_manager2_contact text;
alter table public.pig_companies add column if not exists reg_manager3_name text;
alter table public.pig_companies add column if not exists reg_manager3_contact text;
alter table public.pig_companies add column if not exists company_id_no text;
alter table public.pig_companies add column if not exists apikey text;

alter table public.pig_companies enable row level security;
drop policy if exists "pig_companies select" on public.pig_companies;
create policy "pig_companies select" on public.pig_companies for select using (true);
drop policy if exists "pig_companies insert" on public.pig_companies;
create policy "pig_companies insert" on public.pig_companies for insert with check (true);
drop policy if exists "pig_companies update" on public.pig_companies;
create policy "pig_companies update" on public.pig_companies for update using (true);
drop policy if exists "pig_companies delete" on public.pig_companies;
create policy "pig_companies delete" on public.pig_companies for delete using (true);


-- 2. 거래가격 레코드
create table if not exists public.pig_price_records (
  id               bigint generated by default as identity primary key,
  company_name     text,
  date_str         text,
  reg_date_str     text,
  head_count       real,
  live_weight      real,
  total_amount     real,
  payment_rate     real,
  carcass_head     real,
  carcass_weight   real,
  female_head      real,
  female_weight    real,
  castrated_head   real,
  castrated_weight real,
  male_head        real,
  male_weight      real,
  price_type       text,
  applied_price    real,
  region_group     text,
  registrant       text
);

-- 기존에 이미 만들어진 테이블에도 registrant 컬럼을 보강한다.
alter table public.pig_price_records add column if not exists registrant text;

create index if not exists pig_price_records_company_idx on public.pig_price_records(company_name);
create index if not exists pig_price_records_date_idx on public.pig_price_records(date_str);

alter table public.pig_price_records enable row level security;
drop policy if exists "pig_price_records select" on public.pig_price_records;
create policy "pig_price_records select" on public.pig_price_records for select using (true);
drop policy if exists "pig_price_records insert" on public.pig_price_records;
create policy "pig_price_records insert" on public.pig_price_records for insert with check (true);
drop policy if exists "pig_price_records update" on public.pig_price_records;
create policy "pig_price_records update" on public.pig_price_records for update using (true);
drop policy if exists "pig_price_records delete" on public.pig_price_records;
create policy "pig_price_records delete" on public.pig_price_records for delete using (true);
